export const TRACK_COURSES = {
  "ai-engineering": [
    {
      code: "AI-101",
      title: "Python & Math for AI",
      level: "Foundation",
      duration: "5 weeks",
      hours: 60,
      summary: "Programming fluency plus the linear algebra, calculus, and statistics that every model depends on.",
      outcomes: [
        "Write clean, tested Python with typing and virtual environments",
        "Manipulate data with NumPy and pandas at speed",
        "Reason about vectors, matrices, gradients, and probability",
      ],
      tools: ["Python", "NumPy", "pandas", "Jupyter", "Git"],
      lessons: [
        { week: "Week 1", title: "Python foundations", topics: ["Types, control flow, functions", "Modules, virtualenv, pip", "Testing with pytest"], deliverable: "CLI data cleaner" },
        { week: "Week 2", title: "Data wrangling", topics: ["pandas DataFrames", "Joins, groupby, reshaping", "Missing data strategies"], deliverable: "Messy dataset cleanup" },
        { week: "Week 3", title: "Linear algebra for ML", topics: ["Vectors & matrices", "Dot products, norms", "Eigenvectors and PCA intuition"] },
        { week: "Week 4", title: "Calculus & optimisation", topics: ["Derivatives and gradients", "Gradient descent by hand", "Loss surfaces"] },
        { week: "Week 5", title: "Statistics & probability", topics: ["Distributions", "Hypothesis testing", "Bayes rule in practice"], deliverable: "A/B test analysis report" },
      ],
    },
    {
      code: "AI-201",
      title: "Data Science & Visual Analytics",
      level: "Core",
      duration: "5 weeks",
      hours: 60,
      summary: "Turn raw data into decisions — EDA, feature engineering, dashboards, and storytelling.",
      outcomes: [
        "Run a full exploratory analysis end to end",
        "Engineer features that measurably improve models",
        "Ship a dashboard stakeholders actually use",
      ],
      tools: ["pandas", "Matplotlib", "Plotly", "SQL", "Streamlit"],
      lessons: [
        { week: "Week 1", title: "SQL for analysts", topics: ["Joins & window functions", "CTEs", "Query performance"] },
        { week: "Week 2", title: "Exploratory data analysis", topics: ["Univariate & bivariate analysis", "Outlier handling", "Correlation traps"] },
        { week: "Week 3", title: "Feature engineering", topics: ["Encoding & scaling", "Time-based features", "Leakage prevention"] },
        { week: "Week 4", title: "Visual storytelling", topics: ["Chart selection", "Plotly interactivity", "Narrative structure"] },
        { week: "Week 5", title: "Dashboarding", topics: ["Streamlit apps", "Caching & state", "Deploying to the web"], deliverable: "Live analytics dashboard" },
      ],
    },
    {
      code: "AI-301",
      title: "Machine Learning in Production",
      level: "Core",
      duration: "6 weeks",
      hours: 72,
      summary: "Supervised and unsupervised learning, evaluated honestly and served behind an API.",
      outcomes: [
        "Select, tune, and validate models without fooling yourself",
        "Explain predictions to non-technical stakeholders",
        "Serve a model as a monitored API",
      ],
      tools: ["scikit-learn", "XGBoost", "MLflow", "FastAPI", "Docker"],
      lessons: [
        { week: "Week 1", title: "Regression & regularisation", topics: ["Linear/ridge/lasso", "Bias-variance", "Cross-validation"] },
        { week: "Week 2", title: "Classification", topics: ["Logistic regression, trees", "Imbalanced data", "Precision/recall trade-offs"] },
        { week: "Week 3", title: "Ensembles", topics: ["Random forests", "Gradient boosting", "Hyperparameter search"] },
        { week: "Week 4", title: "Unsupervised learning", topics: ["Clustering", "Dimensionality reduction", "Anomaly detection"] },
        { week: "Week 5", title: "Explainability", topics: ["SHAP values", "Partial dependence", "Model cards"] },
        { week: "Week 6", title: "Serving & monitoring", topics: ["FastAPI inference", "MLflow tracking", "Drift detection"], deliverable: "Deployed prediction API" },
      ],
    },
    {
      code: "AI-401",
      title: "Deep Learning & Computer Vision",
      level: "Advanced",
      duration: "5 weeks",
      hours: 60,
      summary: "Neural networks from first principles through CNNs, transfer learning, and vision deployment.",
      outcomes: [
        "Build and train networks in PyTorch",
        "Apply transfer learning to small datasets",
        "Optimise inference for real hardware",
      ],
      tools: ["PyTorch", "torchvision", "Weights & Biases", "ONNX"],
      lessons: [
        { week: "Week 1", title: "Neural network basics", topics: ["Perceptrons & activations", "Backpropagation", "Training loops"] },
        { week: "Week 2", title: "Training that works", topics: ["Optimisers & schedulers", "Regularisation", "Experiment tracking"] },
        { week: "Week 3", title: "Convolutional networks", topics: ["Convolutions & pooling", "Modern CNN architectures", "Augmentation"] },
        { week: "Week 4", title: "Transfer learning", topics: ["Fine-tuning strategies", "Few-shot datasets", "Evaluation"] },
        { week: "Week 5", title: "Vision in production", topics: ["ONNX export", "Batching & latency", "Edge deployment"], deliverable: "Image classifier API" },
      ],
    },
    {
      code: "AI-501",
      title: "Generative AI, LLMs & Agents",
      level: "Advanced",
      duration: "6 weeks",
      hours: 72,
      summary: "RAG pipelines, fine-tuning, evaluation, and multi-step agents that survive real users.",
      outcomes: [
        "Ship a grounded RAG system with citations",
        "Fine-tune an open model with LoRA",
        "Design agents with tools, memory, and guardrails",
      ],
      tools: ["LangChain", "LlamaIndex", "pgvector", "Hugging Face", "LoRA"],
      lessons: [
        { week: "Week 1", title: "Transformers & prompting", topics: ["Attention intuition", "Prompt patterns", "Token economics"] },
        { week: "Week 2", title: "Embeddings & vector search", topics: ["Chunking strategies", "pgvector indexes", "Hybrid retrieval"] },
        { week: "Week 3", title: "RAG systems", topics: ["Grounding & citations", "Reranking", "Hallucination control"], deliverable: "RAG chatbot over your docs" },
        { week: "Week 4", title: "Fine-tuning", topics: ["Dataset curation", "LoRA/QLoRA", "Eval harnesses"] },
        { week: "Week 5", title: "Agents", topics: ["Tool calling", "Planning loops", "Memory & state"] },
        { week: "Week 6", title: "Safety & cost", topics: ["Guardrails", "Caching", "Observability"] },
      ],
    },
    {
      code: "AI-601",
      title: "Capstone & Interview Lab",
      level: "Capstone",
      duration: "4 weeks",
      hours: 50,
      summary: "One portfolio-grade AI product, plus the interview reps to talk about it convincingly.",
      outcomes: ["Ship a live AI product with real users", "Defend design decisions in system-design rounds", "Leave with a reviewed portfolio and resume"],
      tools: ["GitHub", "Docker", "Cloud hosting", "Mock interviews"],
      lessons: [
        { week: "Week 1", title: "Scoping", topics: ["Problem selection", "Data sourcing", "Success metrics"] },
        { week: "Week 2", title: "Build sprint", topics: ["Weekly mentor critique", "Pair programming", "Iteration"] },
        { week: "Week 3", title: "Ship & measure", topics: ["Deployment", "Analytics", "User feedback loop"], deliverable: "Live capstone" },
        { week: "Week 4", title: "Interview lab", topics: ["ML system design", "Behavioural rounds", "Portfolio review"] },
      ],
    },
  ],

  "cloud-engineering": [
    {
      code: "CL-101",
      title: "Linux, Networking & Scripting",
      level: "Foundation",
      duration: "4 weeks",
      hours: 48,
      summary: "The operating system and network fundamentals every cloud role assumes you already have.",
      outcomes: ["Operate Linux servers confidently", "Debug network issues from first principles", "Automate chores with Bash and Python"],
      tools: ["Linux", "Bash", "systemd", "tcpdump", "Python"],
      lessons: [
        { week: "Week 1", title: "Linux essentials", topics: ["Filesystem & permissions", "Processes & systemd", "Package management"] },
        { week: "Week 2", title: "Shell scripting", topics: ["Bash scripting", "cron & timers", "Log parsing"], deliverable: "Server bootstrap script" },
        { week: "Week 3", title: "Networking", topics: ["TCP/IP, DNS, HTTP", "Firewalls & routing", "Troubleshooting toolkit"] },
        { week: "Week 4", title: "Security basics", topics: ["SSH hardening", "TLS certificates", "Secrets hygiene"] },
      ],
    },
    {
      code: "CL-201",
      title: "AWS & Azure Core Services",
      level: "Core",
      duration: "5 weeks",
      hours: 60,
      summary: "Compute, storage, networking, and identity across the two clouds hiring managers ask about.",
      outcomes: ["Design a secure multi-tier VPC", "Apply least-privilege IAM", "Estimate and control cloud cost"],
      tools: ["AWS", "Azure", "IAM", "S3", "CloudWatch"],
      lessons: [
        { week: "Week 1", title: "Compute", topics: ["EC2 & VM sizing", "Autoscaling", "Load balancers"] },
        { week: "Week 2", title: "Storage & databases", topics: ["S3/Blob tiers", "RDS basics", "Backups & retention"] },
        { week: "Week 3", title: "Networking", topics: ["VPC design", "Subnets & routing", "Private endpoints"], deliverable: "Multi-tier VPC" },
        { week: "Week 4", title: "Identity & security", topics: ["IAM policies", "Roles vs users", "KMS & secrets"] },
        { week: "Week 5", title: "Cost & governance", topics: ["Tagging", "Budgets & alerts", "Right-sizing"] },
      ],
    },
    {
      code: "CL-301",
      title: "Containers & Kubernetes",
      level: "Core",
      duration: "5 weeks",
      hours: 60,
      summary: "From Dockerfile to a production-grade cluster with ingress, autoscaling, and rollouts.",
      outcomes: ["Build lean, secure images", "Operate a Kubernetes cluster", "Roll out safely with zero downtime"],
      tools: ["Docker", "Kubernetes", "Helm", "NGINX Ingress", "Argo CD"],
      lessons: [
        { week: "Week 1", title: "Docker deep dive", topics: ["Layers & caching", "Multi-stage builds", "Image scanning"] },
        { week: "Week 2", title: "Kubernetes objects", topics: ["Pods, Deployments, Services", "ConfigMaps & Secrets", "Probes"] },
        { week: "Week 3", title: "Traffic & scaling", topics: ["Ingress & TLS", "HPA", "Resource requests/limits"] },
        { week: "Week 4", title: "Packaging & GitOps", topics: ["Helm charts", "Argo CD sync", "Environments"], deliverable: "GitOps-managed cluster" },
        { week: "Week 5", title: "Day-2 operations", topics: ["Rollbacks", "Node maintenance", "Debugging pods"] },
      ],
    },
    {
      code: "CL-401",
      title: "Infrastructure as Code & CI/CD",
      level: "Advanced",
      duration: "5 weeks",
      hours: 60,
      summary: "Terraform modules, pipelines, and release engineering that a team can actually maintain.",
      outcomes: ["Model infrastructure in reusable Terraform", "Build pipelines with quality gates", "Ship several times a day safely"],
      tools: ["Terraform", "GitHub Actions", "Ansible", "Vault"],
      lessons: [
        { week: "Week 1", title: "Terraform basics", topics: ["Providers & state", "Variables & outputs", "Remote backends"] },
        { week: "Week 2", title: "Modules at scale", topics: ["Composable modules", "Workspaces", "Drift management"], deliverable: "Reusable module library" },
        { week: "Week 3", title: "Configuration management", topics: ["Ansible playbooks", "Idempotency", "Golden images"] },
        { week: "Week 4", title: "Pipelines", topics: ["Build/test/deploy stages", "Artifact promotion", "Secrets in CI"] },
        { week: "Week 5", title: "Release strategies", topics: ["Blue/green", "Canary", "Feature flags"] },
      ],
    },
    {
      code: "CL-501",
      title: "SRE, Observability & Capstone",
      level: "Capstone",
      duration: "5 weeks",
      hours: 60,
      summary: "Reliability engineering practice plus a capstone platform you own end to end.",
      outcomes: ["Define SLOs and error budgets", "Instrument metrics, logs, and traces", "Run a blameless incident review"],
      tools: ["Prometheus", "Grafana", "Loki", "OpenTelemetry", "PagerDuty"],
      lessons: [
        { week: "Week 1", title: "Observability", topics: ["Metrics vs logs vs traces", "Prometheus & PromQL", "Dashboards"] },
        { week: "Week 2", title: "Reliability", topics: ["SLIs/SLOs", "Error budgets", "Alert design"] },
        { week: "Week 3", title: "Incidents", topics: ["On-call practice", "Game days", "Postmortems"] },
        { week: "Week 4", title: "Capstone build", topics: ["Design review", "Implementation", "Cost check"], deliverable: "Production-grade platform" },
        { week: "Week 5", title: "Certification & interviews", topics: ["AWS/CKA prep", "Scenario rounds", "Portfolio review"] },
      ],
    },
  ],

  "software-engineering": [
    {
      code: "SE-101",
      title: "Web Foundations & JavaScript",
      level: "Foundation",
      duration: "4 weeks",
      hours: 48,
      summary: "Semantic HTML, modern CSS, and the JavaScript model everything else builds on.",
      outcomes: ["Build accessible, responsive layouts", "Reason about async JavaScript", "Use Git in a team workflow"],
      tools: ["HTML", "CSS", "JavaScript", "Git", "Vite"],
      lessons: [
        { week: "Week 1", title: "HTML & accessibility", topics: ["Semantics", "Forms", "ARIA basics"] },
        { week: "Week 2", title: "Modern CSS", topics: ["Flexbox & grid", "Design tokens", "Responsive patterns"], deliverable: "Responsive landing page" },
        { week: "Week 3", title: "JavaScript core", topics: ["Scope & closures", "Arrays & objects", "Modules"] },
        { week: "Week 4", title: "Async & the DOM", topics: ["Promises & async/await", "fetch", "Event handling"] },
      ],
    },
    {
      code: "SE-201",
      title: "React & TypeScript",
      level: "Core",
      duration: "5 weeks",
      hours: 60,
      summary: "Component architecture, state, data fetching, and types that catch bugs before users do.",
      outcomes: ["Structure a real React codebase", "Type components and APIs safely", "Test what matters"],
      tools: ["React", "TypeScript", "TanStack Query", "Vitest", "Playwright"],
      lessons: [
        { week: "Week 1", title: "Components & state", topics: ["Props & composition", "Hooks", "Rendering model"] },
        { week: "Week 2", title: "TypeScript in React", topics: ["Generics", "Discriminated unions", "API typing"] },
        { week: "Week 3", title: "Data fetching", topics: ["Server state vs UI state", "Caching", "Optimistic updates"], deliverable: "Data-driven dashboard" },
        { week: "Week 4", title: "Routing & forms", topics: ["Nested routes", "Validation", "Accessibility"] },
        { week: "Week 5", title: "Testing", topics: ["Unit tests", "Component tests", "E2E with Playwright"] },
      ],
    },
    {
      code: "SE-301",
      title: "Backend with Node & Databases",
      level: "Core",
      duration: "5 weeks",
      hours: 60,
      summary: "APIs, data modelling, auth, and the operational concerns behind a real backend.",
      outcomes: ["Design REST APIs that age well", "Model relational and document data", "Implement secure authentication"],
      tools: ["Node.js", "Express", "PostgreSQL", "MongoDB", "Redis"],
      lessons: [
        { week: "Week 1", title: "HTTP & API design", topics: ["REST conventions", "Validation", "Error contracts"] },
        { week: "Week 2", title: "Relational data", topics: ["Schema design", "Indexes", "Transactions"] },
        { week: "Week 3", title: "Document data & caching", topics: ["MongoDB modelling", "Redis caching", "Queues"] },
        { week: "Week 4", title: "Auth & security", topics: ["Sessions vs JWT", "RBAC", "OWASP top 10"], deliverable: "Secured API service" },
        { week: "Week 5", title: "Performance", topics: ["N+1 queries", "Pagination", "Load testing"] },
      ],
    },
    {
      code: "SE-401",
      title: "AI-Assisted Development & DevOps",
      level: "Advanced",
      duration: "4 weeks",
      hours: 48,
      summary: "Ship faster with AI tooling, and own the pipeline that puts your code in front of users.",
      outcomes: ["Use AI assistants without losing rigour", "Automate build, test, and deploy", "Monitor a live application"],
      tools: ["GitHub Copilot", "Docker", "GitHub Actions", "Sentry"],
      lessons: [
        { week: "Week 1", title: "AI in the workflow", topics: ["Prompting for code", "Review discipline", "Test generation"] },
        { week: "Week 2", title: "Containerising apps", topics: ["Dockerfiles", "Compose for local dev", "Env config"] },
        { week: "Week 3", title: "CI/CD", topics: ["Pipelines", "Preview environments", "Rollbacks"], deliverable: "Automated deploy pipeline" },
        { week: "Week 4", title: "Production hygiene", topics: ["Error tracking", "Logging", "Uptime alerts"] },
      ],
    },
    {
      code: "SE-501",
      title: "System Design & Capstone",
      level: "Capstone",
      duration: "5 weeks",
      hours: 60,
      summary: "Architecture reasoning plus a full-stack product built, shipped, and defended.",
      outcomes: ["Reason about scale trade-offs", "Ship a production full-stack product", "Pass system-design interviews"],
      tools: ["Architecture diagrams", "Cloud hosting", "Mock interviews"],
      lessons: [
        { week: "Week 1", title: "Design fundamentals", topics: ["Scaling patterns", "Caching layers", "Consistency trade-offs"] },
        { week: "Week 2", title: "Case studies", topics: ["Feeds", "Chat", "Marketplaces"] },
        { week: "Week 3", title: "Capstone build", topics: ["Scoping", "Mentor critique", "Iteration"] },
        { week: "Week 4", title: "Ship it", topics: ["Deployment", "Analytics", "Feedback loop"], deliverable: "Live full-stack product" },
        { week: "Week 5", title: "Interview lab", topics: ["DSA refresh", "System design rounds", "Behavioural prep"] },
      ],
    },
  ],
  "future-engineering": [
    {
      code: "FE-101",
      title: "Curious Coders (Ages 6–8)",
      level: "Foundation",
      duration: "8 weeks",
      hours: 24,
      summary: "Computational thinking through stories, puzzles and block coding — screen time with a purpose.",
      outcomes: [
        "Break a problem into ordered steps (algorithmic thinking)",
        "Build animated stories and simple games in ScratchJr/Scratch",
        "Explain sequence, loops and events in their own words",
      ],
      tools: ["ScratchJr", "Scratch", "Unplugged activity kits", "Tynker-style puzzles"],
      lessons: [
        { week: "Week 1", title: "What is a computer?", topics: ["Input, process, output", "Unplugged robot game", "Screen-safety habits"], deliverable: "Paper algorithm for brushing teeth" },
        { week: "Week 2", title: "Sequences", topics: ["Step-by-step instructions", "Debugging a wrong order", "Drag-and-drop basics"], deliverable: "First animated scene" },
        { week: "Week 3", title: "Loops", topics: ["Repeat blocks", "Patterns in art and music", "Counting loops"], deliverable: "Dancing sprite loop" },
        { week: "Week 4", title: "Events", topics: ["When-clicked blocks", "Keyboard control", "Sound triggers"], deliverable: "Interactive greeting card" },
        { week: "Week 5", title: "Storytelling", topics: ["Characters and backdrops", "Dialogue timing", "Scene changes"], deliverable: "Two-scene animated story" },
        { week: "Week 6", title: "Simple games", topics: ["Score idea", "Collisions", "Win and lose states"], deliverable: "Catch-the-star game" },
        { week: "Week 7", title: "Design thinking for kids", topics: ["Who is my user?", "Sketch, build, test", "Kind feedback"], deliverable: "Idea sketchbook page" },
        { week: "Week 8", title: "Showcase", topics: ["Presenting to parents", "Explaining your code", "Reflection"], deliverable: "Showcase project + certificate" },
      ],
    },
    {
      code: "FE-201",
      title: "Block to Text (Ages 8–10)",
      level: "Foundation",
      duration: "10 weeks",
      hours: 30,
      summary: "The bridge year — game logic in Scratch, then the first real lines of typed code and web pages.",
      outcomes: [
        "Use variables, conditionals and lists confidently",
        "Write and style a simple web page with HTML and CSS",
        "Move from blocks to typed syntax without fear",
      ],
      tools: ["Scratch", "HTML", "CSS", "micro:bit", "Google Slides"],
      lessons: [
        { week: "Week 1", title: "Variables", topics: ["Score and lives", "Naming things well", "Watching values change"], deliverable: "Scoreboard game" },
        { week: "Week 2", title: "Conditionals", topics: ["If / else", "Comparisons", "Nested decisions"], deliverable: "Quiz game" },
        { week: "Week 3", title: "Lists & data", topics: ["Storing many items", "Random picks", "Simple data sets"], deliverable: "Flashcard trainer" },
        { week: "Week 4", title: "Game design", topics: ["Levels and difficulty", "Playtesting", "Balancing fun"], deliverable: "Two-level platformer" },
        { week: "Week 5", title: "Hello, text code", topics: ["Why typed code exists", "Syntax and typos", "Editor tour"], deliverable: "First typed program" },
        { week: "Week 6", title: "HTML structure", topics: ["Tags and nesting", "Headings, lists, images", "Links"], deliverable: "About-me page" },
        { week: "Week 7", title: "CSS styling", topics: ["Colours and fonts", "Boxes and spacing", "Simple layout"], deliverable: "Styled hobby page" },
        { week: "Week 8", title: "Physical computing", topics: ["micro:bit basics", "Sensors and LEDs", "Loops in hardware"], deliverable: "Step counter badge" },
        { week: "Week 9", title: "Project build", topics: ["Scoping a small idea", "Milestones", "Peer review"], deliverable: "Personal mini-site" },
        { week: "Week 10", title: "Demo day", topics: ["Slide storytelling", "Live demo practice", "Feedback loop"], deliverable: "Parent showcase demo" },
      ],
    },
    {
      code: "FE-301",
      title: "Python Explorers (Ages 10–12)",
      level: "Core",
      duration: "10 weeks",
      hours: 30,
      summary: "Real Python — logic, functions and data — taught through games, art and everyday problems.",
      outcomes: [
        "Write Python programs with functions and loops",
        "Read and visualise a small real-world dataset",
        "Debug their own code methodically",
      ],
      tools: ["Python", "Thonny / Replit", "Turtle", "pandas basics", "Matplotlib"],
      lessons: [
        { week: "Week 1", title: "Python basics", topics: ["Print, input, variables", "Numbers and strings", "Common errors"], deliverable: "Mad-libs generator" },
        { week: "Week 2", title: "Decisions & loops", topics: ["if/elif/else", "for and while", "Boolean logic"], deliverable: "Number-guessing game" },
        { week: "Week 3", title: "Functions", topics: ["Defining and calling", "Parameters and returns", "Reusing code"], deliverable: "Maths helper toolkit" },
        { week: "Week 4", title: "Turtle art & geometry", topics: ["Coordinates", "Angles and polygons", "Nested loops"], deliverable: "Generative art poster" },
        { week: "Week 5", title: "Lists & dictionaries", topics: ["Collections", "Looping over data", "Lookups"], deliverable: "Class quiz bank" },
        { week: "Week 6", title: "Files & data", topics: ["Reading CSV", "Cleaning simple data", "Averages and counts"], deliverable: "Weather data report" },
        { week: "Week 7", title: "Charts", topics: ["Bar and line charts", "Labels that explain", "Honest graphs"], deliverable: "Data poster" },
        { week: "Week 8", title: "Debugging lab", topics: ["Reading tracebacks", "Print debugging", "Rubber-duck method"] },
        { week: "Week 9", title: "Build sprint", topics: ["Idea to plan", "Version control basics", "Testing your own game"], deliverable: "Playable Python game" },
        { week: "Week 10", title: "Showcase", topics: ["Code walkthrough", "What I'd do next", "Digital portfolio"], deliverable: "Portfolio entry" },
      ],
    },
    {
      code: "FE-401",
      title: "Robotics, IoT & Making (Ages 11–13)",
      level: "Core",
      duration: "10 weeks",
      hours: 36,
      summary: "Hands-on hardware: sensors, motors and microcontrollers that turn code into things that move.",
      outcomes: [
        "Wire and program sensors, motors and displays safely",
        "Build a working robot and an internet-connected device",
        "Document a build like an engineer",
      ],
      tools: ["Arduino", "micro:bit", "Sensors & servos", "Tinkercad", "3D printing"],
      lessons: [
        { week: "Week 1", title: "Electronics safety & circuits", topics: ["Current, voltage, resistance", "Breadboards", "LED circuits"], deliverable: "Blink circuit" },
        { week: "Week 2", title: "Microcontroller coding", topics: ["Arduino sketch structure", "Digital I/O", "Serial monitor"], deliverable: "Traffic-light model" },
        { week: "Week 3", title: "Sensors", topics: ["Light, temperature, distance", "Analogue reading", "Calibration"], deliverable: "Smart night lamp" },
        { week: "Week 4", title: "Motors & movement", topics: ["Servos and DC motors", "Motor drivers", "Speed control"], deliverable: "Two-wheel rover" },
        { week: "Week 5", title: "Robot logic", topics: ["Line following", "Obstacle avoidance", "State machines"], deliverable: "Line-follower bot" },
        { week: "Week 6", title: "3D design", topics: ["Tinkercad modelling", "Tolerances", "Printing a chassis part"], deliverable: "Printed robot mount" },
        { week: "Week 7", title: "IoT basics", topics: ["Wi-Fi modules", "Sending data to the cloud", "Dashboards"], deliverable: "Live sensor dashboard" },
        { week: "Week 8", title: "Engineering documentation", topics: ["Build logs", "Wiring diagrams", "Bill of materials"], deliverable: "Project logbook" },
        { week: "Week 9", title: "Competition sprint", topics: ["Challenge rules", "Iteration under time", "Team roles"], deliverable: "Competition-ready bot" },
        { week: "Week 10", title: "Maker fair", topics: ["Booth demo", "Explaining trade-offs", "Judging feedback"], deliverable: "Maker-fair exhibit" },
      ],
    },
    {
      code: "FE-501",
      title: "AI & Data Literacy for Teens (Ages 13–15)",
      level: "Advanced",
      duration: "10 weeks",
      hours: 36,
      summary: "How AI actually works, how to build with it responsibly, and how to spot when it's wrong.",
      outcomes: [
        "Train and evaluate a simple machine-learning model",
        "Build an app powered by an AI API with safe prompts",
        "Argue clearly about bias, privacy and AI ethics",
      ],
      tools: ["Python", "Teachable Machine", "scikit-learn", "Streamlit", "LLM APIs"],
      lessons: [
        { week: "Week 1", title: "What is intelligence?", topics: ["Rules vs learning", "History in 30 minutes", "Where AI already touches you"] },
        { week: "Week 2", title: "Data is the fuel", topics: ["Collecting data", "Labels and bias", "Privacy basics"], deliverable: "Class dataset (ethically collected)" },
        { week: "Week 3", title: "Train your first model", topics: ["Teachable Machine", "Train/test split", "Accuracy vs confidence"], deliverable: "Image classifier demo" },
        { week: "Week 4", title: "Classical ML", topics: ["Features and labels", "scikit-learn workflow", "Overfitting explained simply"], deliverable: "Prediction notebook" },
        { week: "Week 5", title: "Neural networks intuition", topics: ["Neurons and layers", "Why more data helps", "Compute costs"] },
        { week: "Week 6", title: "LLMs & prompting", topics: ["Tokens and context", "Prompt patterns", "Hallucinations and fact-checking"], deliverable: "Prompt playbook" },
        { week: "Week 7", title: "Build with an AI API", topics: ["API keys and safety", "Chat interfaces", "Guardrails"], deliverable: "Study-buddy app" },
        { week: "Week 8", title: "AI ethics debate", topics: ["Bias case studies", "Deepfakes and consent", "Academic honesty"], deliverable: "Structured debate" },
        { week: "Week 9", title: "Product sprint", topics: ["Problem interviews", "Prototype fast", "Test with real users"], deliverable: "Working AI prototype" },
        { week: "Week 10", title: "Pitch lab", topics: ["Story, demo, impact", "Handling questions", "Next steps"], deliverable: "Pitch deck + demo" },
      ],
    },
    {
      code: "FE-601",
      title: "Innovator Capstone & Olympiad Prep (Ages 13–15)",
      level: "Capstone",
      duration: "8 weeks",
      hours: 24,
      summary: "One real project, taken from problem statement to public demo — plus prep for coding olympiads and school science fairs.",
      outcomes: [
        "Ship a documented project with a live demo",
        "Solve timed algorithmic problems with confidence",
        "Present technical work to a non-technical audience",
      ],
      tools: ["Git & GitHub", "Notion", "Canva", "Competitive programming judges"],
      lessons: [
        { week: "Week 1", title: "Find a real problem", topics: ["Community interviews", "Problem statements", "Scoping to 6 weeks"], deliverable: "Approved project brief" },
        { week: "Week 2", title: "Plan & version control", topics: ["Milestones", "GitHub basics", "Working in a team"], deliverable: "Repo + roadmap" },
        { week: "Week 3", title: "Build sprint 1", topics: ["Core feature first", "Mentor check-in", "Cutting scope"], deliverable: "Working prototype" },
        { week: "Week 4", title: "Algorithms lab", topics: ["Sorting and searching", "Complexity intuition", "Timed practice set"] },
        { week: "Week 5", title: "Build sprint 2", topics: ["Polish and edge cases", "User testing with classmates", "Bug triage"], deliverable: "Beta release" },
        { week: "Week 6", title: "Documentation", topics: ["README that explains", "Screenshots and diagrams", "Credits and licences"], deliverable: "Public project page" },
        { week: "Week 7", title: "Olympiad drills", topics: ["Mock contest", "Common patterns", "Time strategy"], deliverable: "Contest scorecard" },
        { week: "Week 8", title: "Demo day", topics: ["Five-minute story", "Live demo without panic", "Judge Q&A"], deliverable: "Capstone showcase + certificate" },
      ],
    },
  ],
};

export const coursesForTrack = (slug) => TRACK_COURSES[slug] || [];
