export const WORKSHOPS = [
  {
    id: 'w1',
    title: 'Build a RAG chatbot in 3 hours',
    blurb: 'Chunking, embeddings, vector search, and a working answer pipeline you deploy before you leave.',
    track: 'AI',
    format: 'In person',
    date: 'Sat, Aug 22',
    time: '10:00 AM',
    duration: '3 hrs',
    seats: 30,
    seatsLeft: 6,
    price: 'Free',
    host: 'Sarah Chen',
    hostRole: 'AI Engineering Lead',
    featured: true,
  },
  {
    id: 'w2',
    title: 'Kubernetes in production: zero to cluster',
    blurb: 'Pods, services, Helm charts, HPA and a real multi-tier deployment you take home.',
    track: 'Cloud',
    format: 'Online',
    date: 'Sun, Aug 30',
    time: '11:00 AM',
    duration: '3.5 hrs',
    seats: 50,
    seatsLeft: 18,
    price: '₹499',
    host: 'Ravi Shankar',
    hostRole: 'Senior SRE, Zerodha',
    featured: false,
  },
  {
    id: 'w3',
    title: 'Portfolio that gets you hired — live review',
    blurb: 'Submit your portfolio before the session. We dissect 5 portfolios live and rebuild them on screen.',
    track: 'Career',
    format: 'Online',
    date: 'Sat, Sep 6',
    time: '2:00 PM',
    duration: '2 hrs',
    seats: 100,
    seatsLeft: 44,
    price: 'Free',
    host: 'Nisha Kapoor',
    hostRole: 'Career Mentor, TekSchool',
    featured: false,
  },
  {
    id: 'w4',
    title: 'React 19 + Next.js — ship a full-stack app',
    blurb: 'Server components, actions, streaming, edge deployment. Ship a working product end-to-end.',
    track: 'Software',
    format: 'Hybrid',
    date: 'Sun, Sep 14',
    time: '10:00 AM',
    duration: '4 hrs',
    seats: 40,
    seatsLeft: 12,
    price: '₹799',
    host: 'Arjun Mehta',
    hostRole: 'Frontend Engineer, Loom',
    featured: false,
  },
];
